# Generated by Django 3.0.3 on 2020-03-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_linkhash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkhash',
            old_name='link_hash',
            new_name='link',
        ),
    ]
