# Generated by Django 3.0.3 on 2020-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200303_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='info',
        ),
        migrations.AddField(
            model_name='record',
            name='blood_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='children',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='contacts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='hospitals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='recipes',
            field=models.TextField(blank=True),
        ),
    ]
