# Generated by Django 3.0.3 on 2020-03-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200315_0914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MKB_DB',
            new_name='ICD',
        ),
    ]
