# Generated by Django 3.0.3 on 2020-03-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200315_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icd',
            old_name='name',
            new_name='info',
        ),
    ]
