# Generated by Django 3.0.4 on 2020-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200315_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
