# Generated by Django 3.0.4 on 2020-03-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200316_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='serial_number',
            field=models.CharField(max_length=6),
        ),
    ]
