# Generated by Django 3.0.4 on 2020-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200320_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unregistered_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=6)),
                ('auth_code', models.CharField(max_length=8)),
            ],
        ),
    ]
