# Generated by Django 3.0.4 on 2020-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200401_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_moderator',
        ),
        migrations.AddField(
            model_name='hospital',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
