# Generated by Django 3.0.4 on 2020-04-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200412_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystoken',
            name='public_key',
        ),
    ]
