# Generated by Django 3.0.4 on 2020-04-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_keystoken_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystoken',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
