# Generated by Django 3.0.4 on 2020-04-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200413_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hospital'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hospital'),
        ),
        migrations.DeleteModel(
            name='LinkHash',
        ),
    ]
