# Generated by Django 3.0.4 on 2020-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200420_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystoken',
            name='l',
            field=models.BooleanField(default=0),
        ),
    ]
