# Generated by Django 3.0.4 on 2020-04-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_keystoken_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='keystoken',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='keystoken',
            name='user',
        ),
    ]
