# Generated by Django 3.0.4 on 2020-04-20 09:39

from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200420_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='keystoken',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keystoken',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
