# Generated by Django 3.0.4 on 2020-04-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200420_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystoken',
            name='l',
        ),
    ]
