# Generated by Django 3.0.4 on 2020-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_keystoken_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystoken',
            name='logginned',
            field=models.BooleanField(default=0),
        ),
    ]
