# Generated by Django 3.0.4 on 2020-04-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_keystoken_logginned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=8)),
                ('insurance_number', models.CharField(blank=True, max_length=16, null=True)),
                ('illnesses', models.TextField(blank=True)),
                ('hospitals', models.TextField(blank=True)),
                ('recipes', models.TextField(blank=True)),
                ('blood_type', models.TextField(blank=True)),
                ('first_name', models.TextField()),
                ('second_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birthday', models.DateField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
