# Generated by Django 3.0.4 on 2020-04-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_childrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ChildRecord')),
            ],
        ),
    ]
