# Generated by Django 3.0.4 on 2020-04-24 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_migrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
