# Generated by Django 3.0.5 on 2020-04-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_migrationtoken_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystoken',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
