# Generated by Django 3.0.5 on 2020-04-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.IntegerField(blank=True, default=7),
            preserve_default=False,
        ),
    ]
