# Generated by Django 3.0.5 on 2020-05-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_user_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('company', models.TextField()),
                ('phone', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
