# Generated by Django 3.0.5 on 2020-05-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_newpartner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPartner',
            new_name='NewPartnerModel',
        ),
    ]
