# Generated by Django 3.0.5 on 2020-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
