# Generated by Django 3.0.5 on 2020-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200515_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='src',
            field=models.TextField(default='chip.png'),
            preserve_default=False,
        ),
    ]
